softwareFeatureRequest/force-app/main/default/objects/Software_Feature_Request__c/Software_Feature_Request__c.object-meta.xml
<CustomObject>
    <label>Software Feature Request</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Software Feature Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Software Feature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

softwareFeatureRequest/force-app/main/default/objects/Software_Feature_Request__c/fields/Related_Files__c.field-meta.xml
<CustomField>
    <fullName>Related_Files__c</fullName>
    <description>List of Titles of all related files for record</description>
    <label>Related Files</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

softwareFeatureRequest/force-app/main/default/classes/contentDocumentLinkTriggerHandler.cls
public with sharing class contentDocumentLinkTriggerHandler {
    public static void afterInsert(List<ContentDocumentLink> links){
        List<Id> contentDocIds = new List<Id>();
        for (ContentDocumentLink link : links){
            contentDocIds.add(link.ContentDocumentId);
        } 

        Map<Id, ContentDocument> files = new Map<Id, ContentDocument>([SELECT Id, Title FROM ContentDocument WHERE Id IN: contentDocIds]);

        Map<Id, String> sfrIdToLinkTitle = new Map<Id, String>();

        for (ContentDocumentLink link : links){
            if (link.LinkedEntityId.getSobjectType().getDescribe().getName() == 'Software_Feature_Request__c'){
                sfrIdToLinkTitle.put(link.LinkedEntityId, files.get(link.ContentDocumentId).Title);
            }
        }

        List<Software_Feature_Request__c> requestsToUpdate = [SELECT Id, Related_Files__c
                                                              FROM Software_Feature_Request__c
                                                              WHERE Id IN: sfrIdToLinkTitle.keySet()];
        
        for (Software_Feature_Request__c request : requestsToUpdate){
            String filesString = request.Related_Files__c;
            if (String.isBlank(filesString)){
                request.Related_Files__c = sfrIdToLinkTitle.get(request.Id);
            } else {
                request.Related_Files__c = filesString + '; ' + sfrIdToLinkTitle.get(request.Id);
            }
        }
        update requestsToUpdate;
    }
}