softwareFeatureRequest/force-app/main/default/objects/Software_Feature_Request__c/Software_Feature_Request__c.object-meta.xml
<CustomObject>
    <label>Software Feature Request</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Software Feature Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Software Feature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

softwareFeatureRequest/force-app/main/default/objects/Software_Feature_Request__c/fields/Software_Product__c.field-meta.xml
<CustomField>
    <fullName>Software_Product__c</fullName>
    <label>Software Product</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

softwareFeatureRequest/force-app/main/default/objects/Software_Feature_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

softwareFeatureRequest/force-app/main/default/classes/softwareFeatureRequestTrigger_Test.cls
@isTest
public with sharing class softwareFeatureRequestTrigger_Test {
    @isTest static void insertSFRTest(){
        Software_Feature_Request__c request = new Software_Feature_Request__c(
            Title__c = 'Test request',
            Description__c ='Test description',
            Status__c = 'Open',
            Software_Product__c = 'Test prod'
        );

        Test.StartTest();
        insert request;
        Test.StopTest();
        Software_Feature_Request__c updatedReq = [SELECT Id, OwnerId FROM Software_Feature_Request__c WHERE Id=:request.Id];
        System.assertEquals([Select Id FROM Group WHERE Type='Queue' AND Name='Software Feature Request Queue'].Id, updatedReq.OwnerId);
    }
}